name: Spiral100k
version: 1.0
author: Erez
main: me.erez.Spiral100k.Main
description: Fills 100,000 blocks using a spiral pattern
api-version: 1.17

commands:
  start:
    description: fills 100,000 blocks using a spiral pattern